# Site Meta Data
title: Sharewilly WP
author: Münnecke & Vollmers GbR
description: "Mit unserem kostenfreien WordPress-Plugin können deine Webseiten-Besucher Beiträge und Seiten in den Sozialen Medien teilen. Einfach & schnell."
keywords:

# Sharing Options
android_accent: "#00CBC4"
google_analytics:

# Site Config
baseurl: ""
url: "http://sharewilly.github.io/sharewilly"

# Theme Settings
hero_image: "images/default.jpg"
homepage: "http://muennecke-vollmers.de"
download_link: "https://github.com/sharewilly/sharewilly-wp"


# Build settings
markdown: kramdown

permalink: none

sass:
  style: :compressed
  compressed: true

gems:
  - jekyll-sitemap
