# Site Meta Data
title: Sharewilly WP Einfach teilen
author: Münnecke & Vollmers GbR
description: "Mit unserem kostelosen WordPress-Plugin "Sharewilly WP" können deine Webseiten-Besucher Beiträge und Seiten in den Sozialen Medien teilen."
keywords:

# Sharing Options
android_accent: "#00CBC4"
google_analytics:

# Site Config
baseurl: ""
url: "http://sharewilly.github.io/sharewilly"

# Theme Settings
hero_image: "images/default.jpg"
homepage: "http://yoursite.com"
download_link: "#"


# Build settings
markdown: kramdown

permalink: none

sass:
  style: :compressed
  compressed: true

gems:
  - jekyll-sitemap
